#!/usr/bin/env bash

################################################################################
# This Source Code Form is subject to the terms of the Mozilla Public          #
# License, v. 2.0. If a copy of the MPL was not distributed with this          #
# file, You can obtain one at http://mozilla.org/MPL/2.0/.                     #
################################################################################

DESCRIPTION="Reserved for future use."
VERSION="0.0.0"
HOMEPAGE="https://jesus.gg/"
KEYWORDS="[]"
CATEGORIES="[]"
AUTHORS="[\"$(git config user.name) <$(git config user.email)>\"]"
LICENSE_FILE="LICENSE.txt"
LICENSE_TYPE="MPL-2.0"
LICENSE=$(cat "LICENSE.txt")
README_FILE="README.md"
README="\
# {{NAME}}

$DESCRIPTION

## License

> This Source Code Form is subject to the terms of the Mozilla Public
> License, v. 2.0. If a copy of the MPL was not distributed with this
> file, You can obtain one at http://mozilla.org/MPL/2.0/."

base=$(pwd)

for pkg in $*; do
	mkdir -p $pkg/src
	cd $pkg

	echo "$README" | sed "s/{{NAME}}/$pkg/g" >> $README_FILE
	echo "$LICENSE" >> $LICENSE_FILE
	cat $README_FILE | sed 's/^/\/\/! /' >> src/lib.rs

	echo '[package]' >> Cargo.toml
	echo "name = \"$pkg\"" >> Cargo.toml
	echo "description = \"$DESCRIPTION\"" >> Cargo.toml
	echo "version = \"$VERSION\"" >> Cargo.toml
	echo "homepage = \"$HOMEPAGE\"" >> Cargo.toml
	echo "keywords = $KEYWORDS" >> Cargo.toml
	echo "categories = $CATEGORIES" >> Cargo.toml
	echo "license = \"$LICENSE_TYPE\"" >> Cargo.toml
	echo "readme = \"$README_FILE\"" >> Cargo.toml
	echo "authors = $AUTHORS" >> Cargo.toml
	echo "edition = \"2018\"" >> Cargo.toml

	cargo publish --allow-dirty

	cd $base
	rm -r $pkg
done
